bands:                  # Optical bands to load from Landsat tiles
  - 'band4'
  - 'band5'
  - 'band2'
  - 'band3'

quality_maps:
  - 'pixel_qa'


coordinates:
  - 198026               # WRS coordinate


198026:
  dates:                # Date of tiles to load at this coordinate
    - '2013-07-12'
    - '2013-12-03'
    - '2014-03-09'
    - '2014-04-10'
    - '2015-03-12'
    - '2015-08-03'
    - '2017-02-13'
    - '2018-04-21'
    - '2018-05-07'
    - '2018-07-26'
    - '2018-09-12'
    - '2018-10-14'
    - '2019-06-27'
    - '2020-01-21'
    - '2020-02-06'
    - '2020-04-10'
