bands:                  # Optical bands to load from Landsat tiles
  - 'band4'
  - 'band5'
  - 'band2'
  - 'band3'

quality_maps:
  - 'pixel_qa'


coordinates:
  - 198026               # WRS coordinate


198026:
  dates:                # Date of tiles to load at this coordinate
    - '2018-04-21'
    - '2018-05-07'
    - '2018-07-26'
    - '2018-09-12'
    - '2018-10-14'
