################################################################################
#   SPECIFICATIONS ON MODIS SCENES RASTERS LOADING
################################################################################


# TARGET COORDINATE REFERENCE SYSTEM FOR REPROJECTION
EPSG: 4326


# ORDERED NAMING OF BAND FILES TO LOAD
bands:
  - 'B01'
  - 'B02'
  - 'B03'
  - 'B04'


# NAMING OF QUALITY ASSESSMENT FILES
quality_maps:
  - 'B01qa'
  - 'B02qa'
  - 'B03qa'
  - 'B04qa'


# MODIS COORDINATES OF SCENES TO CONSIDER
coordinates:
  - - 18                # Horizontal tile modis coordinate
    - 4                 # Vertical tile modis coordinate


# DATES OF SCENS TO CONSIDER BY MODIS COORDINATE
18/04:
    dates:
    - '2013-07-12'
    - '2013-12-03'
    - '2014-03-09'
    - '2014-04-10'
    - '2015-03-12'
    - '2015-08-03'
    - '2017-02-13'
    - '2018-04-21'
    - '2018-05-07'
    - '2018-07-26'
    - '2018-09-12'
    - '2018-10-14'
    - '2019-06-27'
    - '2020-01-21'
    - '2020-02-06'
    - '2020-04-10'
