################################################################################
#   SPECIFICATIONS ON PATCH EXTRACTION FOR LANDSAT-MODIS
################################################################################

# LIST OF RASTERS DATES TO CONSIDER
dates:
  - '2013-07-12'
  - '2013-12-03'
  - '2014-03-09'
  - '2014-04-10'
  - '2015-03-12'
  - '2015-08-03'
  - '2017-02-13'
  - '2018-04-21'
  - '2018-05-07'
  - '2018-07-26'
  - '2018-09-12'
  - '2018-10-14'
  - '2019-06-27'
  - '2020-01-21'
  - '2020-02-06'
  - '2020-04-10'

# DIMENSIONS OF PATCHES TO EXTRACT
patch_size:
  - 256    # height
  - 256    # width


# PERCENTAGE OF NON-CONTAMINED PIXELS FOR A PATCH TO BE ACCEPTED
validity_threshold: 0.99
