dates:                # Date of tiles to load at this coordinate
  - '2018-04-21'
  - '2018-05-07'
  - '2018-07-26'
  - '2018-09-12'
  - '2018-10-14'


patch_size:
  - 256
  - 256

validity_threshold: 0.99
