stages:
  stack_bands_and_reproject_modis:
    cmd: python src/prepare_data/preprocessing/stack_and_reproject/stack_and_reproject_modis.py
      --root=/data/raw_data/modis/mcd43a4_aws/ --o=data/reprojected/modis --scenes=src/prepare_data/config/scenes/modis.yaml
    deps:
    - /data/raw_data/modis/mcd43a4_aws/
    - src/prepare_data/config/scenes/modis.yaml
    - src/prepare_data/preprocessing/stack_and_reproject/stack_and_reproject_modis.py
    outs:
    - data/reprojected/modis
  stack_bands_and_reproject_landsat:
    cmd: python src/prepare_data/preprocessing/stack_and_reproject/stack_and_reproject_landsat.py
      --root=/data/temporary/shahine/raw_data/landsat/landsat-8/france --o=data/reprojected/landsat
      --scenes=src/prepare_data/config/scenes/landsat.yaml
    deps:
    - /data/temporary/shahine/raw_data/landsat/landsat-8/france
    - src/prepare_data/config/scenes/landsat.yaml
    - src/prepare_data/preprocessing/stack_and_reproject/stack_and_reproject_landsat.py
    outs:
    - data/reprojected/landsat
  patch_extraction_modis_landsat:
    cmd: python src/prepare_data/preprocessing/patch_extraction/extract_patches_modis_landsat.py
      --modis_root=data/reprojected/modis --landsat_root=data/reprojected/landsat
      --scenes_specs=src/prepare_data/config/patch_extraction/modis_landsat.yaml --o=data/patches/modis_landsat
    deps:
    - data/reprojected/landsat
    - data/reprojected/modis
    - src/prepare_data/config/patch_extraction/modis_landsat.yaml
    - src/prepare_data/preprocessing/patch_extraction/extract_patches_modis_landsat.py
    outs:
    - data/patches/modis_landsat
  prepare_ESTARFM_inputs:
    cmd: python src/prepare_data/preprocessing/ESTARFM/prepare_inputs.py --patch_dir=data/patches/modis_landsat
      --o=data/patches/modis_landsat_ESTARFM --estarfm_out=data/experiments_outputs/modis_landsat_fusion/ESTARFM
    deps:
    - data/patches/modis_landsat
    - src/prepare_data/preprocessing/ESTARFM/prepare_inputs.py
    outs:
    - data/patches/modis_landsat_ESTARFM
