  ###############################################################################
#
#   TEMPLATE CONFIGURATION FILE FOR SYNTHETIC TOY IMAGERY GENERATION
#
###############################################################################


############################################
#   INPUT DATA
############################################
# Path to synthetic product to derive
latent_product_path: "../toy-products/hr_optical"



############################################
#   RESOLUTION SPECIFICATIONS
############################################

# Derived product dimensions i.e. relative spatial resolution
target_size:
  width: 50
  height: 50

# Derived product temporal resolution in days
temporal_res: 10



############################################
#   IMAGE-LEVEL TRANSFORM SPECIFICATIONS
############################################

# Image-level corruption transformation of loaded synthetic product
corruption:
  # Name of transformation to build from TRANSFORMS registry
  name: 'cloud'

  ## VOLATILE ARTEFACTS
  # Clouds sampling size in pixels
  sampling_scale: 512

  # Clouds density - higher = denser, choose in [0., 1.5]
  cloud_density: 0.1

  # Clouds sparsity - lower = coarser, choose around 1.0
  cloud_sparsity: 1.5

  # Likelihood of clouding a frame
  cloud_probability: 0.5


# Image-level geometric transformation of loaded synthetic product
deformation:
  # Name of transformation to build from TRANSFORMS registry
  name: 'tangential_scale_distortion'

  # Input image dimensions = dimenions of loaded synthetic product
  image_width: 2048
  image_height: 2048

  # Discretization in rows/cols of input image for tangential scale distortion emulation
  mesh_columns_cells: 20
  mesh_rows_cells: 20

  # Tangential scale distortion axis ; 0 = cols ; 1 = rows
  axis: 0

  # Scale distortion growth rate, leave empty for max growth rate ; must be <= 4 / length_distortion_axis
  growth_rate: 0.00195


# Image-level postprocessing transformation applied to downsampled image
postprocess:


############################################
#   IMAGE AGGREGATION SPECIFICATIONA
############################################
aggregation:
  # Name of aggregation to build from AGGREGATE registry
  name: convolution

  # Convolution heat kernel parameters
  kernel:
    sigma: 1.5



############################################
#   REPRODUCIBILITY
############################################
seed: 73
