  ###############################################################################
#
#   TEMPLATE CONFIGURATION FILE FOR SYNTHETIC TOY IMAGERY GENERATION
#
###############################################################################


############################################
#   INPUT DATA
############################################
# Path to synthetic product to derive
latent_product_path: "../data/toy-products/dummy_cloud_dataset/clean_optical/"



############################################
#   RESOLUTION SPECIFICATIONS
############################################

# Derived product dimensions i.e. relative spatial resolution
target_size:
  width: 256
  height: 256

# Derived product temporal resolution in days
temporal_res: 1



############################################
#   IMAGE-LEVEL TRANSFORM SPECIFICATIONS
############################################

# Image-level corruption transformation of loaded synthetic product
corruption:
  # Name of transformation to build from TRANSFORMS registry
  name: 'cloud_and_brightness'

  ## VOLATILE ARTEFACTS
  # Clouds sampling size in pixels
  sampling_scale: 256

  # Clouds density - higher = denser, choose in [0., 1.5]
  cloud_density: 0.1

  # Clouds sparsity - lower = coarser, choose around 1.0
  cloud_sparsity: 1.5

  # Likelihood of clouding a frame
  cloud_probability: 0.5

  ## BRIGHTNESS ALTERATION
  # Multiplication factor
  mul:
    min: 0.6
    max: 1.3

  # Bias factor, pixel valued in [0, 1]
  add:
    min: -0.1
    max: 0.1

  # Random seed for product static brightness transform
  seed: 7

# Image-level geometric transformation of loaded synthetic product
deformation:

# Image-level postprocessing transformation applied to downsampled image
postprocess:


############################################
#   IMAGE AGGREGATION SPECIFICATION
############################################
aggregation:


############################################
#   REPRODUCIBILITY
############################################
seed: 73
