###############################################################################
#
#   TEMPLATE CONFIGURATION FILE FOR SYNTHETIC TOY IMAGERY GENERATION
#
###############################################################################


############################################
#   INPUT DATA
############################################
ts:
  # Path to Time Series .ts dataset
  path: 'data/ts/Multivariate_ts/Cricket/Cricket_TRAIN.ts'

  # Choose dimensionality of generating time serie, must be <= actual dimensionality of loaded time serie
  ndim: 5

  # Number of classes of the time serie, <= actual number of classes
  nclass: 12


############################################
#   PRODUCT SPECIFICATIONS
############################################
product:
  # Product dimensions
  size:
    width: 256
    height: 256

  # Bands = channels ; must match time serie dimensionality
  nbands: 5

  # Horizon = number of time steps
  horizon: 31

  # Background color in 0 - 255
  background_color: 0

  # Number of voronoi polygons
  n_polygons: 16


############################################
#   RANDOM SAMPLER
############################################
random_sampler:
  # Name of random sampler to use in {'gaussian', 'gaussian_process'}
  name: 'gaussian_process'
  # Standard deviation when using iid gaussian noise
  std: 1.
  # Kernel when using gaussian process
  kernel:
    # Kernel name in {'rbf', 'rational_quadratic', 'sin_squared', 'constant'}
    name: 'rbf'
    length_scale: 2.5



############################################
#   EXPORT FORMAT
############################################
astype: 'h5'



############################################
#   REPRODUCIBILITY
############################################
seed: 73
