###############################################################################
#
#   TEMPLATE CONFIGURATION FILE FOR SYNTHETIC TOY IMAGERY GENERATION
#
###############################################################################


############################################
#   INPUT DATA
############################################
# Path to MNIST dataset
mnist_path: 'data/mnist'
# Path to Time Series .ts dataset
ts_path: 'data/ts/Multivariate_ts/ArticularyWordRecognition/ArticularyWordRecognition_TRAIN.ts'
# Batch size = nb of digits to patch on image
batch_size: 47

############################################
#   PRODUCT SPECIFICATIONS
############################################
product:
  # Product dimensions
  size:
    width: 1024
    height: 1024

  # Bands = channels ; must match time serie dimensionality
  nbands: 3

  # Horizon = number of time steps
  horizon: 3

  # Background color in 0 - 255
  background_color: 0

  # Digits patching strategy in {'random', 'grid'} ; see wiki on Product
  mode: 'grid'
  grid_size:
    width: 152
    height: 152

  # Geometric Transformation to apply to digits
  transform:
    name: 'digit'         # Name of transformation to build from TRANSFORMS registry
    min_digit_scale: 3    # Minimum rescaling factor for digits
    max_digit_scale: 6    # Maximum rescaling factor for digits

############################################
#   EXPORT FORMAT
############################################
astype: 'h5'

############################################
#   REPRODUCIBILITY
############################################
seed: 73
