mnist_path: 'data/mnist'
ts_path: 'data/ts/Multivariate_ts/ArticularyWordRecognition/ArticularyWordRecognition_TRAIN.ts'
batch_size: 47
product:
  size:
    width: 1024
    height: 1024
  nbands: 3
  horizon: 3
  background_color: 0
  mode: 'grid'
  grid_size:
    width: 152
    height: 152
  transform:
    name: 'digit'
    min_digit_scale: 3
    max_digit_scale: 6
astype: 'h5'
seed: 73
