mnist_path: 'data/mnist'
ts_path: 'data/ts/Multivariate_ts/ArticularyWordRecognition/ArticularyWordRecognition_TRAIN.ts'
batch_size: 64
product:
  size:
    width: 1024
    height: 1024
  nbands: 3
  horizon: 32
  background_color: 0
  mode: 'grid'
  grid_size:
    width: 128
    height: 128
  transform:
    name: 'digit'
    min_digit_scale: 2
    max_digit_scale: 5
astype: 'h5'
seed: 73
