mnist_path: 'data/mnist'
ts_path: 'data/ts/Multivariate_ts/ArticularyWordRecognition/ArticularyWordRecognition_TRAIN.ts'
batch_size: 64
product:
  size:
    width: 2048
    height: 2048
  nbands: 3
  horizon: 32
  background_color: 0
  mode: 'grid'
  grid_size:
    width: 256
    height: 256
astype: 'jpg'
seed: 73
