############################################
#   EXPERIMENT
############################################
experiment:
  # Name of dataset to build from EXPERIMENTS registry
  name: 'cgan_cloud_removal'

  # Random seed
  seed: 73

  # Optional path to checkpoint from which to resume training
  chkpt:

  # Maximum number of epochs to run training for
  max_epochs: 32

  # Precision
  precision: 32

############################################
#   DATASETS
############################################
dataset:
  # Name of dataset to build from DATASETS registry
  name: dummy_cloud_removal

  # Path to dataset
  root: "data/toy/dummy_cloud_removal/"

  # Split ratio in [0, 1] - sum must be == 1
  split:
    train: 0.8
    val: 0.2

  # Dataloading specifications
  dataloader:
    # Number of frames per batch
    batch_size: 32

    # Number of workers for loading
    num_workers: 4


############################################
#   NETWORK
############################################
model:
  generator:
    # Name of generator to build from MODELS registry
    name: 'unet'

    # Input image size
    input_size:
      - 8           # channels
      - 256         # height
      - 256         # width

    # Nb of filters from first to last encoding convolutional block
    enc_filters:
      - 32
      - 64
      - 64

    # Parameters of encoding convolutional blocks
    enc_kwargs:
      - {bn: False, relu: False}
      - {}
      - {}

    # Nb of filters from first to last decoding convolutional block
    dec_filters:
      - 64
      - 32
      - 5

    # Parameters of decoding convolutional blocks
    enc_kwargs:
      - dropout: 0.2
      - {}
      - {}


  discriminator:
    # Name of discriminator to build from MODELS registry
    name: 'patchgan'

    # Input image size
    input_size:
      - 13          # channels
      - 256         # height
      - 256         # width

    # Nb of filters from first to last encoding convolutional block
    n_filters:
      - 16
      - 32
      - 32

    # Parameters of convolutional blocks
    conv_kwargs:
      - bn: False
      - {}
      - {bn: False, relu: False}




############################################
#   OPTIMIZER - LR SCHEDULER
############################################
# Specify optimizer params for LightningModule.configure_optimizers method
optimizer:
  generator:
    lr: 0.001
  discriminator:
    lr: 0.001

# Specify lr scheduler params for LightningModule.configure_optimizers method
lr_scheduler:



############################################
#   CALLBACKS
############################################
early_stopping:
  # Name of callback to build from CALLBACKS registry
  name: 'early_stopping'

  # Quantity to monitor
  monitor: 'gen_loss'

  # Number of epochs to wait without improvement
  patience: 3
