############################################
#   EXPERIMENT
############################################
experiment:
  # Name of dataset to build from EXPERIMENTS registry
  name: 'dummy_cloud_removal'

  # Random seed
  seed: 73

  # Optional path to checkpoint from which to resume training
  chkpt:

  # Maximum number of epochs to run training for
  max_epochs: 32

  # Precision
  precision: 32

############################################
#   DATASETS
############################################
dataset:
  # Name of dataset to build from DATASETS registry
  name: dummy_cloud_removal

  # Path to dataset
  root: "/data/toy/dummy_cloud_removal/"

  # Split ratio in [0, 1] - sum must be == 1
  split:
    train: 0.8
    val: 0.2


############################################
#   NETWORK
############################################
model:
  # Name of model to build from MODELS registry
  name: 'autoencoder'

  # Input image size
  input_size:
    - 8           # channels
    - 256         # height
    - 256         # width

  # Nb of channels of output
  out_channels: 5

  # Nb of filters from first to last encoding convolutional block
  enc_filters:
    - 32
    - 8

  # Nb of filters from first to last decoding convolutional block
  dec_filters:
    - 32
    - 8


############################################
#   CALLBACKS
############################################
early_stopping:
  # Name of callback to build from CALLBACKS registry
  name: 'early_stopping'

  # Quantity to monitor
  monitor: 'val_loss'

  # Number of epochs to wait without improvement
  patience: 3
