############################################
#   EXPERIMENT
############################################
experiment:
  # Name of dataset to build from EXPERIMENTS registry
  name: 'resnet_modis_landsat_temporal_resolution_fusion'

  # Random seed
  seed: 73

  # Optional path to checkpoint from which to resume training
  chkpt:

  # Maximum number of epochs to run training for
  max_epochs: 64

  # Precision
  precision: 32




############################################
#   DATASETS
############################################
dataset:
  # Name of dataset to build from DATASETS registry
  name: modis_landsat_temporal_resolution_fusion

  # Path to dataset
  root: "data/not-so-toy/patches/landsat_modis"

  # Split ratio in [0, 1] - sum must be == 1
  split:
    train: 0.7
    val: 0.15
    test: 0.15

  # Dataloading specifications
  dataloader:
    # Number of frames per batch
    batch_size: 16

    # Number of workers for loading
    num_workers: 32




############################################
#   NETWORK
############################################
model:
  # Name of model to build from MODELS registry
  name: 'resnet'

  # Input image size
  input_size:
    - 8           # channels
    - 256         # height
    - 256         # width

  # Number of channels of output image
  out_channels: 4

  # Nb of residual layers
  n_residuals: 32

  # Nb of filters of residual layers
  n_filters_residuals: 256

  # Parameters of residual convolutional blocks
  residuals_kwargs:
    kernel_size: 3
    padding: 1
    residual_scaling: 0.1




############################################
#   OPTIMIZER - LR SCHEDULER
############################################
# Specify optimizer params for LightningModule.configure_optimizers method
optimizer:
  lr: 0.0002
  betas:
    - 0.5
    - 0.999

# Specify lr scheduler params for LightningModule.configure_optimizers method
lr_scheduler:
  gamma: 0.99




############################################
#   CALLBACKS
############################################
early_stopping:

# Specs of checkpoint saving callback
model_checkpoint:
  # Quantity to monitor
  monitor: 'val_loss'

  # Save top k models
  save_top_k: 1

  # Monitor modality
  mode: 'min'





############################################
#   TESTING
############################################
testing:
  # Path to checkpoint file to load for testing
  chkpt:
